name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: run build-add.sh
        run: bash ci/build-app.sh

      - name: test
        run: bash ci/unit-test-app.sh
