env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: My-step
        uses: actions/checkout@v2

      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Build: 
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Build
        run: bash ci/build-app.sh

      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .

  Test:
    needs: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Test
        run: bash ci/unit-test-app.sh

  Docker-image:
    needs: [Build, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .


      - name: give permision
        run: chmod +x ci/build-docker.sh && chmod +x ci/push-docker.sh

      - name: run docker, build and push
        run: export GIT_COMMIT="GA-$GITHUB_SHA" && bash ci/build-docker.sh && bash ci/push-docker.sh

  Component-test:
    runs-on: ubuntu-latest
    needs: Docker-image
    container: krust19/micronaut-app:latest

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
          
      - name: running
        run: chmod +x ci/component-test.sh && ci/component-test.sh