name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: My-step
        uses: actions/checkout@v2
      - run: bash ci/build-app.sh

      - name: Test
        run: bash ci/unit-test-app.sh
